### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Huray-hub** [Huray-hub/eclass-utils#3]
- [x] Reverse engineer and replicate auth mechanism
- [x] Assignments
  - [x] Get credentials from yaml
  - [x] Get enrolled courses
  - [x] Fetch assignments
  - [x] Polish error handling
  - [x] Logging
  - [x] Performance optimization
  - [x] Prettify output (table format, colors etc)
  - [x] CLI flags
  - [x] CI/CD
  - [x] "installation process"
  - [x] Extra features
    - [x]  Filter out expired deadlines
    - [x] Exclude courses from fetch
    - [x] Exclude assignments per course by keywords
    - [x] Print raw text (for the Unix philosophers)
    - [x] Export assignments to calendar ics file
    - [x] Include only courses marked as favorite option
    - [x] Encrypt password when storing to config.yml (and decrypt on read)
  - [x] Improve Wiki
